openapi: 3.0.3
info:
  title: DashNET
  description: DashNET modern project management dashboard
  termsOfService: http://swagger.io/terms/
  contact:
    email: info@dashnet.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0_beta
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8081
tags:
  - name: Task
    description: Everything about TASKS
paths:
  /tasks:
    get:
      summary: Retrieve all users
      description: Retrieves a list of all users in the system
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The unique identifier for the task
                        creatorId:
                          type: integer
                          description: The ID of the task creator
                        assigneeId:
                          type: integer
                          description: The ID of the task assignee
                        teamId:
                          type: integer
                          description: The ID of the team the task belongs to
                        commentTbId:
                          type: integer
                          description: The ID of the comment thread associated with the task
                        status:
                          type: integer
                          description: The status of the task
                        createdDate:
                          type: string
                          format: date
                          description: The date the task was created
                        deadlineDate:
                          type: string
                          format: date
                          description: The deadline date for the task
                        title:
                          type: string
                          description: The title of the task
                        description:
                          type: string
                          description: The description of the task

  /tasks/title/{titleName}:
    get:
      summary: Get tasks by title
      description: Retrieves tasks matching the provided title (using 'like' SQL operator)
      parameters:
        - name: titleName
          in: path
          required: true
          schema:
            type: string
          description: The title to search for
      responses:
        '200':
          description: Tasks matching the title
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '404':
          description: Tasks not found

  /tasks/description/{description}:
    get:
      summary: Get tasks by description
      description: Retrieves tasks matching the provided description (using 'like' SQL operator)
      parameters:
        - name: description
          in: path
          required: true
          schema:
            type: string
          description: The description to search for
      responses:
        '200':
          description: Tasks matching the description
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '404':
          description: Tasks not found

  /tasks/count:
    get:
      summary: Get task count
      description: Retrieves counts of different task statuses
      responses:
        '200':
          description: Counts of different task statuses
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      todo:
                        type: integer
                        description: Count of tasks to do
                      total:
                        type: integer
                        description: Total count of tasks
                      inProgress:
                        type: integer
                        description: Count of tasks in progress
                      notStarted:
                        type: integer
                        description: Count of tasks not started
                      done:
                        type: integer
                        description: Count of tasks done
                  status:
                    type: integer
                    description: Response status
        '404':
          description: Counts not found
