version: '3.8'

services:

  spring-be:
    container_name: dashNet-spring
    profiles:
      - 'no-admin'
      - 'spring-mysql'
      - 'spring-mysql-admin'
      - 'default'
    build:
      context: .
      dockerfile: ./docker/Spring.Dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${SPRING_REPLICAS}
    ports:
      - ${SPRING_PORT}:8080
    volumes:
      - .:/app
    networks:
      - dash-net
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DB_PASSWORD}

  frontend-production:
    container_name: dashNet-react-fe-pro
    build:
      context: .
      dockerfile: docker/React.Production.Dockerfile
    ports:
      - ${FE_PRODUCTION_PORT}:80
    profiles:
      - 'production'

  frontend-development:
    container_name: dashNet-react-fe
    profiles:
      - 'react'
      - 'no-admin'
      - 'default'
    build:
      context: .
      dockerfile: docker/React.Dockerfile
    ports:
      - ${NODE_PORT}:3000
    restart: unless-stopped
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: ${NODE_REPLICAS}
    volumes:
      - './src/main/ui/src:/app/src:delegate'
    environment:
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=${NODE_PORT}
      - CHOKIDAR_USEPOLLING=${NODE_POLLING}
      - WATCHPACK_POLLING=${NODE_POLLING}

  mysql-db:
    build:
      context: .
      dockerfile: docker/MySql.Dockerfile
    container_name: dashNet-mysql
    profiles:
      - 'mysql'
      - 'no-admin'
      - 'spring-mysql'
      - 'mysql-admin'
      - 'spring-mysql-admin'
      - 'default'
    image: dashnet-mysql-image
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${MYSQL_REPLICAS}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - "dashnet-mysql:/var/lib/mysql"
    networks:
      - dash-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin
    profiles:
      - 'phpadmin'
      - 'mysql-admin'
      - 'spring-mysql-admin'
      - 'default'
    links:
      - mysql-db
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${PMA_REPLICAS}
    ports:
      - ${PMA_PORT}:80
    networks:
      - dash-net

networks:
  dash-net: { }

volumes:
  dashnet-mysql: